name: Deploy & Build
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd apps/heidaho.com
            git pull
            pnpm install
            npx nuxi generate
            echo 'Deployment complete'
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
